try{stManager.done('lang1_0.js');}catch(e){}
audio_do_you_want_flash='Бажаєте перейти на сторінку встановлення програвача?';
audio_you_need_flash='Для того, щоб скористатися аудіосервісом, Вам необхідно встановити Flash-програвач.';
box_cancel='Скасувати';
box_close='Закрити';
box_loading='Завантаження...';
box_no='Нi';
box_restore='Відновити';
box_save='Зберегти';
box_send='Надіслати';
box_yes='Так';
captcha_cancel='Скасувати';
captcha_enter_code='Введіть код з зображення';
captcha_send='Надіслати';
claims_flood_error='Ви вже відправили кілька скарг. Будь ласка, спробуйте через деякий час.';
datepicker_date_format='{day} {month} {year}';
datepicker_month_format='{month} {year}';
functions_sure_delete='Ви дійсно хочете видалити цей запис?';
global_add='Додати';
global_add_media_more='Більше..';
global_back='Назад';
global_Complain_video='Поскаржитись';
global_cancel='Скасувати';
global_captcha_input_here='Введіть код сюди';
global_changes_saved='Зміни збережено';
global_charged_zone_continue='Продовжити';
global_charged_zone_title='Попередження';
global_close='Закрити';
global_continue='Продовжити';
global_day_label='День:';
global_delete='Видалити';
global_done='Готово';
global_dont_delete='Не видаляти';
global_edit='Редагувати';
global_error='Помилка';
global_error_occured='Помилка';
global_lang_box_title='Вибір мови';
global_media_selector_more='Ще';
global_min='Згорнути';
global_mobile_need_validation='Для цієї дії необхідна прив&#39;язка номера телефону. {link}Прив&#39;язати номер »{/link}';
global_money_amount_rub=['','%s рубль','%s рублі','%s рублів'];
global_money_amount_rub_text=['','рубль','рублі','рублів'];
global_money_amount_votes_text=['','голос','голоси','голосів'];
global_month_label='Місяць:';
global_not_activated_title='Прив&#39;язка номера телефону';
global_num_date_year_time=['','{num_day}.{month}.{short_year} {num_hour}:{minute}','вчора, {num_hour}:{minute}','сьогодні, {num_hour}:{minute}','завтра, {num_hour}:{minute}'];
global_n_votes=['','%s голос','%s голоси','%s голосів'];
global_online=['','Online','Online'];
global_online_sm=['','online','online'];
global_privacy_except='крім:';
global_rating_box_header='Рейтинг';
global_recommended_exceeded=['','Рекомендований обсяг перевищено на %s знак.','Рекомендований обсяг перевищено на %s знаки.','Рекомендований обсяг перевищено на %s знаків.'];
global_recommended_lines=['','Рекомендований обсяг перевищено на %s рядок.','Рекомендований обсяг перевищено на %s рядки.','Рекомендований обсяг перевищено на %s рядків.'];
global_reply_to='відповідь {user}';
global_save='Зберегти';
global_search_not_found='За запитом {search} нічого не знайдено.';
global_to_top='Вгору';
global_try_to_activate='Втомилися вводити коди? Пройдіть безкоштовну {link}валідацію через мобільний телефон »{/link}';
global_unknown_error='Невідома помилка';
global_vkontakte='ВКонтактi';
global_warning='Попередження';
global_write_msg='Повідомлення';
global_X_people=['','%s особа','%s особи','%s осіб'];
global_year_label='Рік:';
graph_day_fullmon_year_hour='{day} {dayMonth} {year}, {hour}:00';
graph_day_fullmon_year_hour_min='{day} {dayMonth} {year}, {hour}:{min}';
guest_password='Пароль';
Higher_education='Вища освiта';
head_fr_online_tip='Показати друзів онлайн';
head_search_results='Результати пошуку';
Interests='Захоплення:';
im_already_shown='Вікно миттєвих повідомлень уже запущено, Вам потрібно просто перейти на нього.';
im_already_shown_title='Миттєве повідомленння';
its_spam='Це спам';
its_spam_sm='Це спам';
leftAd_Details='Докладнiше';
leftAd_details='докладнiше';
leftAd_news='Новини';
leftAd_reminder='Нагадування';
left_delete_unpaid_gifts_text='Ви впевнені, що хочете видалити всі неоплачені подарунки?';
left_delete_unpaid_gifts_title='Видалення подарунків';
Military_place='Вiйськова частина:';
Month1='Сiчень';
Month10='Жовтень';
Month10_of='Жовтня';
Month11='Листопад';
Month11_of='Листопада';
Month12='Грудень';
Month12_of='Грудня';
Month1_of='Сiчня';
Month2='Лютий';
Month2_of='Лютого';
Month3='Березень';
Month3_of='Березня';
Month4='Квiтень';
Month4_of='Квiтня';
Month5='Травень';
Month5_of='Травня';
Month6='Червень';
Month6_of='Червня';
Month7='Липень';
Month7_of='Липня';
Month8='Серпень';
Month8_of='Серпня';
Month9='Вересень';
Month9_of='Вересня';
month10sm_of='жов';
month10_of='жовтня';
month11sm_of='лис';
month11_of='листопада';
month12sm_of='гру';
month12_of='грудня';
month1sm_of='сiч';
month1_of='сiчня';
month2sm_of='лют';
month2_of='лютого';
month3sm_of='бер';
month3_of='березня';
month4sm_of='квi';
month4_of='квiтня';
month5sm_of='тра';
month5_of='травня';
month6sm_of='чер';
month6_of='червня';
month7sm_of='лип';
month7_of='липня';
month8sm_of='сер';
month8_of='серпня';
month9sm_of='вер';
month9_of='вересня';
pagination_allpages='Усi';
privacy_custom_title='Налаштування приватності';
privacy_N_friends_more=['','і ще %s друга','і ще %s друзів','і ще %s друзів'];
privacy_N_friends_some=['','і ще %s друг','і ще %s друзів','і ще %s друзів'];
privacy_options_advanced_settings='Усі, крім..';
privacy_options_advanced_settings_dat='всім, крім..';
privacy_options_all_users='Усі користувачі';
privacy_options_all_users_dat='всім користувачам';
privacy_options_friends_and_friends_dat='друзям і друзям друзів';
privacy_options_friends_only='Лише друзі';
privacy_options_friends_only_dat='лише друзям';
privacy_options_nobody='Ніхто';
privacy_options_only_me='Лише я';
privacy_options_only_me_dat='лише мені';
privacy_options_some_friends='Деякі друзі';
privacy_options_some_friends_dat='деяким друзям';
privacy_options_some_friend_lists='Деякі списки друзів';
privacy_options_some_friend_lists_dat='деяким спискам друзів';
privacy_save='Зберегти';
Religion='Світогляд:';
Remove_from_friends='Видалити з друзiв';
rate_you_have_N_unused=['','У Вас <b>%s</b> невикористаний голос.','У Вас <b>%s</b> невикористані голоси.','У Вас <b>%s</b> невикористаних голосів.'];
Save='Зберегти';
Secondary_education='Середня освiта';
Sex='Стать:';
Sex_fm='Жiноча';
Sex_m='Чоловiча';
search_by_app='в додатках';
search_by_audio='в аудіозаписах';
search_by_event='за подіями';
search_by_goods='у товарах';
search_by_group='за групами';
search_by_note='в нотатках';
search_by_person='за іменами';
search_by_question='у питаннях';
search_by_status='по новинах';
search_by_topic='за темами';
search_by_video='у відеозаписах';
select_chair_not_selected='- Не обрано -';
select_chair_select='Введіть назву';
select_city_not_found='Місто не знайдене';
select_city_not_selected='- Не обрано -';
select_city_other_city='- Інший -';
select_city_select='Введіть назву';
select_class_not_selected='- Не обрано -';
select_country_full_list='- Повний перелік -';
select_country_not_found='Країна не знайдена';
select_country_not_selected='- Не обрано -';
select_country_select='Введіть країну';
select_district_not_selected='- Не обрано -';
select_eduform_not_selected='- Не обрано -';
select_edustatus_not_selected='- Не обрано -';
select_fac_not_selected='- Не обрано -';
select_house_not_found='Будинок не знайдено';
select_house_not_selected='- Не обрано -';
select_house_select='Введіть номер';
select_place_not_found='Назву не знайдено';
select_place_not_selected='- Не обрано -';
select_place_select='Введіть назву';
select_school_not_selected='- Не обрано -';
select_school_select='Введіть назву';
select_station_not_selected='- Не обрано -';
select_street_not_found='Вулицю не знайдено';
select_street_not_selected='- Не обрано -';
select_street_select='Введіть назву';
select_uni_not_selected='- Не обрано -';
select_uni_select='Введіть назву';
sex_fm='жiноча';
sex_m='чоловiча';
share_go='Перейти';
Today='Сьогоднi';
Town='Мiсто:';
text_exceeds_symbol_limit=['','Допустимий обсяг перевищено на %s знак.','Допустимий обсяг перевищено на %s знаки.','Допустимий обсяг перевищено на %s знаків.'];
text_N_symbols_remain=['','Лишився %s знак.','Лишилось %s знаки.','Лишилось %s знаків.'];
today='сьогоднi';
top_search='Шукати {query}';
top_search_news='Шукати {query} в новинах';
Updates='Оновлення';
updates='оновлення';
videofile_num=['','відеозапис','відеозаписи','відеозаписів'];
votes_flex=['','голос','голоси','голосів'];
Work_place='Мiсце роботи:';
yesterday='вчора';
// section = 0; version = 213;

friends_no_user_selected='Ви не обрали жодного користувача.';
// section = 2; version = 92;

audio_add_to_audio='Додати до Моїх Аудіозаписів';
audio_add_to_group='Додати в аудіозаписи спільноти';
audio_album_no_recs='В альбомі ще немає аудіозаписів.';
audio_change_album_name='Змінити назву';
audio_claim_delete='видалити аудіозапис';
audio_claim_objection='заповнивши спеціальну форму';
audio_claim_warning='Аудіозапис {audio} було вилучено з публічного доступу у зв&#39;язку зі зверненням правовласника.';
audio_claim_warning_objection='Аудіозапис {audio} було вилучено з публічного доступу у зв&#39;язку зі зверненням правовласника.<br><br>Ви можете оскаржити скаргу, {objection_link}, або {delete_link}, який порушує авторські права.';
audio_claim_warning_text='Аудіозапис {audio} було вилучено з публічного доступу у зв&#39;язку зі зверненням правовласника.<br><br>Ви можете {delete_link}, який порушує авторські права.';
audio_claim_warning_title='Спірний аудіозапис';
audio_common_list='загальний список';
audio_crap_warning='Аудіозапис {audio} був вилучений з публічного доступу у зв&#39;язку з відсутністю культурної цінності.';
audio_crap_warning_text='Аудіозапис {audio} був вилучений з публічного доступу у зв&#39;язку з відсутністю культурної цінності.<br><br>Ви можете {delete_link}.';
audio_crap_warning_title='Спірний аудіозапис';
audio_current_playing_from='Зараз лунає — {playlist}';
audio_delete='видалити';
audio_delete_album='Видалити альбом';
audio_delete_album_are_you_sure='Ви впевнені, що хочете видалити цей альбом?';
audio_delete_album_button='Видалити';
audio_delete_album_title='Видалення альбому';
audio_delete_all_title='Видалення аудіозаписів';
audio_edit_additionally='Додатково';
audio_edit_album='Редагувати альбом';
audio_edit_album_title='Редагування альбому';
audio_edit_cancel='Скасувати';
audio_edit_deleting='Видалення аудіозапису';
audio_edit_deleting_error='Помилка при видаленні аудіозапису:';
audio_edit_dont_show_search='Не відображати під час пошуку';
audio_edit_edit='Зберегти';
audio_edit_editing='Редагування аудіозапису';
audio_edit_name='Назва';
audio_edit_no='Немає';
audio_edit_noname='Без назви';
audio_edit_singer='Виконавець';
audio_edit_sure_delete='Ви дійсно бажаєте видалити цей аудіозапис?';
audio_edit_text='Слова пісні';
audio_edit_unknown='Невідомий виконавець';
audio_edit_yes='Так';
audio_enter_album_name='Введіть назву альбому';
audio_error_loading='Під час завантаження аудіозапису відбулася помилка. Спробуйте оновити сторінку.';
audio_export_tip='Транслювати на мою сторінку';
audio_friends_feed='Оновлення друзів';
audio_global_search_found=['','У пошуку знайдено %s аудіозапис','У пошуку знайдено %s аудіозаписи','У пошуку знайдено %s аудіозаписів'];
audio_group_no_recs='На сторінці спільноти ще немає аудіозаписів.';
audio_header='Мої Аудіозаписи';
audio_loading_error='Виникла помилка, код помилки: {code}';
audio_lyrics_not_found='Текст пісні не знайдено';
audio_need_flash_title='Необхідний Flash-програвач';
audio_new_album_title='Новий альбом';
audio_not_found='Аудіозапис не знайдено';
audio_no_audios_found='За запитом {query} не знайдено жодного аудіозапису';
audio_no_rec_load_msg='Тут Ви можете зберігати Ваші аудіозаписи.<br>Для того, щоб завантажити Ваш перший аудіозапис, {link}натисніть тут{/link}.';
audio_no_your_recs='У Вас поки немає аудіозаписів';
audio_only_foreign_music='тільки закордонні';
audio_popular_audios='Популярні аудіозаписи';
audio_recommended_audios='Рекомендовані аудіозаписи';
audio_repeat_tooltip='Повторювати цю композицію';
audio_search_enter_audio_name='Ведіть назву чи виконавця';
audio_search_not_found='По запиту {search} нічого не знайдено.';
audio_search_results='Результати пошуку';
audio_show_more_audios='Показати більше аудіозаписів';
audio_show_recommendations='Показати схожі';
audio_shuffle='Перемішати';
audio_success_msg_multiple='Усі аудіозаписи успішно завантажено.';
audio_title_search='Пошук за запитом {q}';
audio_uploading_over='Завантаження завершено';
audio_upl_not_enabled_ingroup='У цій групі відключені аудіозаписи, тому завантаження <br>аудіофайлів недоступне.';
audio_user_no_recs='У користувача ще немає аудiозаписiв.';
// section = 3; version = 89;

apps_addapp='Додати додаток';
apps_addedtogroup='Додаток додано в групу';
apps_app_settings='Налаштування додатку';
apps_balance_minus_X_done=['','Ви зменшили баланс додатку на <b>%s</b> голос.','Ви зменшили баланс додатку на <b>%s</b> голоси.','Ви зменшили баланс додатку на <b>%s</b> голосів.'];
apps_balance_plus_X_done=['','Ви поповнили баланс додатку на <b>%s</b> голос.','Ви поповнили баланс додатку на <b>%s</b> голоси.','Ви поповнили баланс додатку на <b>%s</b> голосів.'];
apps_cancel='Скасувати';
apps_change_settings='Налаштувати';
apps_delete_admin_title='Видалення адміністратора';
apps_done='Готово';
apps_dont_show='Більше не показувати';
apps_edit='редагувати';
apps_editapp='Редагувати';
apps_global_search_found=['','У пошуку знайдено %s додаток','У пошуку знайдено %s додатки','У пошуку знайдено %s додатків'];
apps_last_notifications='Останні сповіщення';
apps_merchant_payment_title='Оплата покупки';
apps_my_apps='Мої додатки';
apps_need_X_votes=['','Додаток просить Вас внести <b>%s</b> голос.','Додаток просить Вас внести <b>%s</b> голоси.','Додаток просить Вас внести <b>%s</b> голосів.'];
apps_noappsingroup2='В групi не пiдключено жодного додатка.';
apps_no_apps_found='За запитом {query} не знайдено жодного додатка.';
apps_no_notifications='Немає сповіщень';
apps_of_group='Додатки спільноти';
apps_remove='Прибрати';
apps_search_in_apps='Пошук по додатках';
apps_show_more_apps='Показати більше додатків';
apps_X_apps_found=['','Знайдено %s додаток','Знайдено %s додатки','Знайдено %s додатків'];
apps_youaddednoapps='Ви ще не пiдключили жодного додатка.';
apps_you_have_no_notifies='У Вас немає жодного оповіщення';
app_comments_hidecomms='Приховати коментарі';
app_comments_showcomms='Відобразити коментарі';
// section = 4; version = 208;

video_add_to_public='Повернути до публічного доступу';
video_comment_placeholder='Коментувати..';
video_delete_from_public='Вилучити з доступу';
video_delete_tag='Видалити відмітку';
video_flash_needed='Для перегляду необхідна найновіша версія {flash_player} .';
// section = 5; version = 85;

notes_cancel='Скасувати';
notes_done='Готово';
notes_livejournal_delete='Видалити цей запис з <b>LiveJournal</b>.';
// section = 7; version = 22;

admin_added_items_digit_search='пошук цифр';
// section = 8; version = 9;

blank_note_not_found='Нотатка не знайдена';
// section = 10; version = 36;

events_ajax_inv_declined_spam='Запрошення відхилено і відмічено як спам.';
events_fri='Пт';
events_goto_search='Перейти до пошуку';
events_mon='Пн';
events_sat='Сб';
events_sun='Нд';
events_thu='Чт';
events_tue='Вт';
events_wed='Ср';
// section = 13; version = 21;

fave_return_to_fave='Закладки';
// section = 14; version = 9;

gifts_cansend_X_gifts=['','Ви можете надіслати не більше <b>%s</b> подарунка.','Ви можете надіслати не більше <b>%s</b> подарунків.','Ви можете надіслати не більше <b>%s</b> подарунків.'];
gifts_confirm_N_Votes=['','<b>%s</b> голос','<b>%s</b> голоси','<b>%s</b> голосів'];
gifts_confirm_send_to_N_friends=['','Подарунок буде відправлений %s другу ({votes}). Продовжити?','Подарунок буде відправлений %s друзям ({votes}). Продовжити?','Подарунок буде відправлений %s друзям ({votes}). Продовжити?'];
gifts_free_send_left=['','Ви вибрали безплатний подарунок і можете надіслати його <b>%s другу</b>.','Ви вибрали безплатний подарунок і можете надіслати його <b>%s друзям</b>.','Ви вибрали безплатний подарунок і можете надіслати його <b>%s друзям</b>.'];
gifts_rate_increase='При відправці цього подарунку рейтинг користувача збільшується на <b>{gifts_count}</b>.';
gifts_X_gifts=['','<b>%s</b> подарунок','<b>%s</b> подарунка','<b>%s</b> подарунків'];
gifts_X_votes=['','%s голос','%s голоси','%s голосів'];
// section = 15; version = 40;

groups_admins='Адміністратори';
groups_admins_of_group='Адміністратори спільноти';
groups_appl_rejected='Заявку відхилено.';
groups_assign='Призначити';
groups_assigned='Учасник призначений керівником.';
groups_assigning_manager='Призначення керівника';
groups_cancel='скасувати';
groups_cancel2='Скасувати';
groups_create_enter='Будь ласка, введіть назву спільноти';
groups_create_new='Створення нової спільноти';
groups_delete_manager='Видалення керівника';
groups_deleting_link='Видалення посилання';
groups_edit='Редагувати';
groups_editing_link='Редагування посилання';
groups_enter_name='Назва';
groups_enter_post='Введіть посаду:';
groups_group_admin='Адміністратор спільноти';
groups_group_create_button='Створити спільноту';
groups_inv_cancelled='Запрошення відмінено.';
groups_limit_message='На жаль, Ви не можете бути підписані більше, ніж на 5000 спільнот одночасно.';
groups_limit_title='Досягнуто межу';
groups_no='Ні';
groups_officers='Керівники';
groups_officers_of_group='Керівники спільноти';
groups_partic_accepted='Учасника прийнято.';
groups_partic_deleted='Учасника видалено.';
groups_reject_invint='Відхилити запрошення';
groups_sure_delete_link='Ви дійсно бажаєте видалити посилання на цю групу?';
groups_sure_delete_manager='Ви дійсно бажаєте видалити цю людину з керівників?';
groups_to_all_posts='до всіх записів';
groups_unbanned='Користувача видалено з бан-листу';
groups_yes='Так';
// section = 17; version = 126;

help_ccform_legal_need_email='Ви повинні висловити згоду з тим, що вказана Вами адреса електронної пошти може використовуватися Адміністрацією Сайту для подальших комунікацій за скаргою.';
help_ccform_legal_need_inform='Ви повинні висловити свою згоду з тим, що зазначені вище дані про правовласників, про Вас і Ваша скарга будуть спрямовані особі, зазначеній в якості користувача, який розмістив спірний контент.';
help_ccform_legal_need_is_owner='Ви повинні підтвердити, що являєтесь уповноваженим представником правовласника вказаного суперечного контенту.';
help_ccform_legal_need_perjury='Ви повинні підтвердити, що усвідомлюєте юридичні наслідки, які може спричинити безпідставне обвинувачення в порушенні авторських прав.';
help_ccform_legal_need_unauthorized='Ви повинні підтвердити, що спірний контент використовується без згоди правовласника.';
help_ccform_natural_need_email='Ви повинні висловити згоду з тим, що вказана Вами адреса електронної пошти може використовуватися Адміністрацією Сайту для подальших комунікацій за скаргою.';
help_ccform_natural_need_inform='Ви повинні висловити свою згоду з тим, що зазначені вище дані про Вас і Ваша скарга будуть спрямовані особі, зазначеній в якості користувача, який розмістив спірний контент.';
help_ccform_natural_need_owner='Ви повинні підтвердити, що є правовласником зазначеного спірного контента.';
help_ccform_natural_need_perjury='Ви повинні підтвердити, що усвідомлюєте юридичні наслідки, які може спричинити безпідставне обвинувачення в порушенні авторських прав.';
help_ccform_natural_need_unauthorized='Ви повинні підтвердити, що спірний контент використовується без Вашого дозволу.';
help_ccform_need_rules='Ви повинні погодитися з умовами правил розгляду скарг, пов&#39;язаних з розміщенням контенту на сайті ВКонтакте.';
help_ccobjection_need_email='Ви повинні дати згоду на те, що вказана Вами адреса електронної пошти може використовуватися Адміністрацією Сайту для подальших комунікацій за скаргою.';
help_ccobjection_need_inform='Ви повинні дати згоду на те, що зазначені вище дані про Вас і Ваше заперечення будуть спрямовані правовласнику.';
help_ccobjection_need_rules='Ви повинні погодитися з умовами правил розгляду скарг, пов&#39;язаних з розміщенням контенту на сайті ВКонтакте.';
// section = 18; version = 132;

login_enter='Увійти';
login_wrong_email_pwd='Вказано неправильний логін або пароль.';
// section = 21; version = 73;

mail_cancel='Скасувати';
mail_close='Закрити';
mail_delete='Видалити';
mail_deleteall1='Видалити всi повiдомлення';
mail_delete_all_spam='Видалити всі повідомлення, що містять спам?';
mail_error='Помилка';
mail_marked_as_spam='Повідомлення помічене як спам і видалене.';
// section = 22; version = 109;

payments_amount_rubles=['','рубль','рублі','рублів'];
payments_amount_votes=['','голос','голоси','голосів'];
payments_cancel='Скасувати';
payments_card_verified_msg='Ви підтвердили, що ви є власником картки.';
payments_close='Закрыти';
payments_error='Помилка';
payments_fee_full='Комісія {amount} р. ({percent}%)';
payments_fee_votes=['','Сума: %s рубль','Сума: %s рублі','Сума: %s рублів'];
payments_min_amount_limit_rubles='Мінімальна кількість рублів для оплати через обрану платіжну систему - %s.';
payments_msg_deleted='Повідомлення видалено.';
payments_N_tries_left_msg=['','У Вас залишилася одна спроба.','У Вас залишилося %s спроби.','У Вас залишилося %s спроб.'];
payments_payment_system_submit='Сплатити';
payments_please_enter_money='Будь ласка, введіть суму платежу.';
payments_really_start_over_msg='Ви насправді хочете почати процедуру з початку?';
payments_really_use_other_msg='Ви насправді хочете використовувати іншу карту для проведення платежів?';
payments_send='Надіслати';
payments_thanks_for_comm='Дякуємо за ваш відгук.';
payments_verify_start_over_header='Ви впевнені?';
payments_verify_sum_currency='Валюта авторизації транзакції:';
payments_verify_sum_dialog='Введіть суму авторизаційної транзакції:';
payments_verify_sum_header='Введіть суму';
payments_verify_sum_howto_dialog='Суму авторизаційної транзакції Ви можете дізнатися:<br><ul class="listing"><li><span> звернувшись у службу підтримки клієнтів банку по телефону, вказаному на зворотньому боці Вашої картки. Повідомте оператору, що Ви тільки що здійснили оплату в інтернет-магазині, і для підтвердження прав на використання картки, Вам необхідна інформація про суму транзакції. Вас попросять ідентифікувати себе, після чого нададуть інформацію.</span></li><li><span> через систему віддаленого банківського обслуговування інтернет-банк/банк-клієнт - у разі надання даної послуги банком-емітентом;</span></li><li><span> за допомогою послуги SMS-інформування - у разі надання даної послуги банком-емітентом.</span></li></ul>';
payments_verify_sum_howto_header='Як дізнатися суму авторизаційної транзакції';
payments_wait_verifying_msg='Будь-ласка зачекайте. Перевірка може тривати 5-10 хвилин.';
payments_wrong_sum_msg='Суму авторизаційної транзакції введено неправильно, спробуйте знову.';
payments_your_comm='Ваш вiдгук';
payment_no_more_tries_msg='Суму авторизаційної транзакції введено неправильно. Ви використали всі спроби для цієї авторизаційної транзакції. Вам необхідно розпочати процес з початку, натиснувши на кнопку &quot;Підтвердити&quot;';
// section = 28; version = 81;

photos_cancel='Скасувати';
photos_done='Готово';
photos_stop_uploading='Перервати завантаження';
photos_uploading_warning='Завантаження фотографій ще триває. Ви впевнені, що хочете покинути сторінку і перервати завантаження?';
photos_viewer_exit='Вийти з режиму перегляду';
photo_comment_marked_as_spam='Коментар помічений як спам';
photo_dont_close='Будь ласка, не закривайте це вікно, поки фотографії не завантажаться.';
photo_rotating='Повертаємо';
photo_uploading_photo='Відбувається завантаження фотографій';
// section = 30; version = 83;

ads_image_too_small='Ви намагаєтеся завантажити занадто маленьку фотографію.<br>Виберіть фотографію більшого розміру і повторіть спробу.';
profile_enter_post='Написати повідомлення..';
profile_mention_not_found='Сторінку не знайдено';
profile_mention_start_typing='Почніть вводити ім&#39;я друга або назву спільноти';
profile_oph_crop_desc='Залишилося вибрати квадратну область для маленьких фотографій.<br>Обрана мініатюра буде використовуватися в новинах, особистих повідомленнях і коментарях.';
// section = 31; version = 167;

reg_sex_not_set='- Не задано -';
// section = 35; version = 39;

search_nothing_found='Нічого не знайдено';
// section = 36; version = 52;

stats_data_empty='Нема даних';
stats_day_mon='{day} {month}';
stats_day_month_year='{day} {month} {year}';
stats_error_loading='Помилка при завантаженні';
stats_good_browser_box_msg='К сожалению, Ваш браузер не поддерживает отображение графиков статистики.<br><br>Чтобы использовать все возможности сайта, Вы можете загрузить и установить один из современных браузеров:';
stats_loading='Завантаження...';
stats_no_data='Відсутні вхідні дані';
// section = 38; version = 76;

paysupp_error='Помилка';
// section = 39; version = 187;

wall_post_not_found='Запис не знайдено';
wall_publish_now='Опублікувати зараз';
wall_reply_to_post='Коментувати..';
wall_reply_to_post_link='Коментувати';
wall_send='Надiслати';
// section = 41; version = 113;

vkontakte_ru='ВКонтакті';
// section = 42; version = 124;

fans_block_fan='Заблокувати';
fans_no_fans='На цього користувача ще ніхто не підписаний.';
fans_no_idols='Цей користувач ще не підписаний ні на одну сторінку.';
fans_show_all_fans='Показати всіх підписників';
fans_show_all_idols='Показати всі цікаві сторінки';
// section = 54; version = 14;

abuse_goto_support='Якщо Ви хочете видалити сторінку, створену від Вашого імені, або свою стару сторінку — будь ласка, зверніться <a class="wikiVkLink" href="http://vk.com/support?act=new&amp;from=abuse">в підтримку</a>. ';
// section = 58; version = 11;

offers_reban='Повернути до списку';
offers_unban='Видалити зі списку';
// section = 59; version = 20;

mobile_act_not_activated_header='Прив&#39;язка номера телефону';
mobile_apps_catalog_app_members=['','%s учасник','%s учасники','%s учасників'];
mobile_edit_country_null='Не обрано';
mobile_photos_albums_edit_album_btn='Зберегти';
mobile_photos_edit_save_btn='Зберегти';
mobile_profile_work_label='Мiсце роботи:';
mobile_wall_publish_postponed='Опублікувати зараз';
mobile_zphoto_save_btn='Зберегти';
// section = 61; version = 369;


var langConfig = {"id":1,"numDel":"<span class=\"num_delim\"> <\/span>","numDelS":" ","numDec":",","prepTags":["{prep_with}","{prep_With}","{prep_about}","{prep_About}","{prep_into}","{prep_Into}"],"prep":[["{prep_with},{prep_With}","С*,З*,Льв*","со,Со"],["{prep_with},{prep_With}","*,Са*,Се*,Сё*,Си*,Со*,Су*,Сэ*,Сю*,Ся*,За*,Зе*,Зё*,Зи*,Зо*,Зу*,Зэ*,Зю*,Зя*","с,С"],["{prep_about},{prep_About}","А*,О*,У*,И*,Э*","об,Об"],["{prep_about},{prep_About}","*","о,О"],["{prep_into},{prep_Into}","В*,Ф*,Льв*","во,Во"],["{prep_into},{prep_Into}","*,Ва*,Ве*,Вё*,Ви*,Во*,Ву*,Вэ*,Вю*,Вя*,Фа*,Фе*,Фё*,Фи*,Фо*,Фу*,Фэ*,Фю*,Фя*","в,В"]],"parent":0,"timeSys":["24hour"],"yearOffset":0,"flexLast":false,"revOrder":false,"RTL":false,"numRules":{"int":[[100,[11,12,13,14],3],[10,[1],1],[10,[2,3,4],2],["*",0,3]],"float":2},"sexRules":[[1,2],["*",1]],"larr":"&larr;","rarr":"&rarr;"};
var market_currency_count = ['RUB','UAH','KZT','USD','EUR'];

var qArr = [[0, getLang('search_by_person'), '', 'people', 0],
[1, getLang('search_by_group'), '', 'groups', 0x00800000],
[2, getLang('search_by_event'), '', 'events', 0x01000000],
[3, getLang('search_by_audio'), '', 'audio',  0x00000002],
[4, getLang('search_by_video'), '', 'video',  0x00400000],
[5, getLang('search_by_ad'), '', 'ads', 0x00000100],
[6, getLang('search_by_app'), '', 'apps', 0x00000020],
[7, getLang('search_by_question'), '', 'questions', 0x00000040],
[8, getLang('search_by_note'), '', 'notes', 0x02000000],
[9, getLang('search_by_topic'), '', 'topics', 0x00800000],
[11, getLang('search_by_status'), '', 'statuses', 0]];

var year_offset = langConfig.yearOffset;
var larr = langConfig.larr;
var rarr = langConfig.rarr;