object Form1: TForm1
  Left = 247
  Top = 213
  Width = 464
  Height = 232
  Caption = #1060#1086#1085#1086#1074#1099#1081' '#1088#1080#1089#1091#1085#1086#1082
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 13
end
